# Site settings
title: Lens
description: Just another fine responsive site template by <a href="http://html5up.net">HTML5 UP</a>
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/astean1001

# Build settings
markdown: kramdown
